#!/bin/bash

source $LIB_PATH/power.sh;

function install_mongo(){ [[ ! -z $(check_user "mongodb") ]]||{ update_package_repo;info "install necessary dependencies ...";install_apt_package mongodb;su mongodb -s /bin/bash -c "mkdir -p /var/lib/mongodb/data/{db,logs}";random_mongo_passwd;};};
function random_mongo_passwd(){ local __pwd=$(head -c 500 /dev/urandom|md5sum|cut -d" " -f1);local __sql="db.createUser({user:'root', pwd:'$__pwd', roles:['root']})";filename=$(head -c 500 /dev/urandom|md5sum|cut -d" " -f1);sed -i 's;--auth;--noauth;g' $SUPERVISOR_HOME/mongodb.ini;(supsctl restart mongodb &>$TMP_PATH/$filename&&info "database start success.")||{ fail "database start failure.";cat $TMP_PATH/$filename;};sleep 16;mongo 127.0.0.1:27017/admin --eval "$__sql";echo -e $__pwd &> $HUB_HOME/mongo.passwd;};

function install_mysql(){ [[ ! -z $(check_user "mysql") ]]||{ update_package_repo;info "install necessary dependencies ...";install_apt_all_package "mariadb-client mariadb-server";su mysql -s /bin/bash -c "mysql_install_db --datadir='/var/lib/mysql/data' --skip-name-resolve --rpm --no-defaults";random_mysql_passwd;};};
function random_mysql_passwd(){ local __user=root;local __pwd=$(head -c 500 /dev/urandom|md5sum|cut -d" " -f1);filename=$(head -c 500 /dev/urandom|md5sum|cut -d" " -f1);(supsctl restart mariadb &>$TMP_PATH/$filename&&info "database start success.")||{ fail "database start failure.";cat $TMP_PATH/$filename;};sleep 16;/usr/bin/mysqladmin -u "$__user" password "$__pwd";/usr/bin/mysqladmin -u "$__user" reload;echo -e $__pwd &> $HUB_HOME/mysql.passwd;};

function install_elastic(){ [[ ! -z $(check_user "elastic") ]]||{ install_sys_user elastic elastic;rm -rf /usr/lib/jvm/default-java;update_package_repo;info "install necessary dependencies ...";install_apt_all_package "default-jdk maven golang";chown -R elastic:elastic /var/lib/elastic /usr/share/elasticsearch /usr/share/kibana;su elastic -s /bin/bash -c "source $LIB_PATH/power.sh&&configs $LIB_PATH/config.d/elastic";random_elastic_passwd;su elastic -s /bin/bash -c "source $LIB_PATH/power.sh&&configs $LIB_PATH/config.d/kibana";};};
function random_elastic_passwd(){ local __user=elastic;filename=$(head -c 500 /dev/urandom|md5sum|cut -d" " -f1);(supsctl restart all &>$TMP_PATH/$filename&&info "database start success.")||{ fail "database start failure.";cat $TMP_PATH/$filename;};sleep 64;[[ ! -x "/usr/share/elasticsearch/bin/elasticsearch-setup-passwords" ]]||{ su "$__user" -s /bin/bash -c "echo -e 'y\n'|/usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto"|grep PASSWORD|awk '{cmd="echo "$NF" > /humsys/hub.d/"$2".passwd";system(cmd)}';};};

function install_rasp(){ [[ ! -z $(check_user "raspcloud") ]]||{ echo 19921011 &> $HUB_HOME/rasp.passwd;[[ "network" == $1 ]]||random_rasp_passwd;[[ "network" == $1 ]]||random_iast_passwd;install_sys_user shadow raspcloud;cd /usr/share/jenkins;jar cvfm jenkins.war ./META-INF/MANIFEST.MF .;mv /usr/share/jenkins/jenkins.war /var/lib/raspcloud/jenkins.war;chown -R raspcloud:shadow /var/lib/raspcloud /usr/share/jenkins /usr/share/onedev /usr/share/raspcloud;su raspcloud -s /bin/bash -c "source $LIB_PATH/power.sh&&configs $LIB_PATH/config.d/rasp";};};
function random_rasp_passwd(){ local __pwd=$(head -c 500 /dev/urandom|md5sum|cut -d" " -f1);local __sql="db.createUser({user:'root', pwd:'$__pwd', roles:[{role:'dbOwner', db:'rasp'}]})";(supsctl restart mongodb &>$TMP_PATH/$filename&&info "database start success.")||{ fail "database start failure.";cat $TMP_PATH/$filename;};sleep 16;mongo 127.0.0.1:27017/rasp --eval "$__sql";echo -e $__pwd &> $HUB_HOME/rasp.passwd;};
function random_iast_passwd(){ local __u="iast";local __p="iast";local __h=$1;[[ ! -z "$1" ]]||__h="127.0.0.1";local __user=root;local __pwd=$(cat $HUB_HOME/mysql.passwd);local __db=rasp;local __sql="CREATE DATABASE IF NOT EXISTS \`$__db\` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;";(supsctl restart mariadb &>$TMP_PATH/$filename&&info "database start success.")||{ fail "database start failure.";cat $TMP_PATH/$filename;};sleep 16;mysql -u "$__user" -h "$__h" --password="$__pwd" -e "$__sql";mysql -u "$__user" -h "$__h" --password="$__pwd" -e "CREATE USER '$__u'@'$__h' IDENTIFIED BY '$__p';";mysql -u "$__user" -h "$__h" --password="$__pwd" -e "GRANT ALL PRIVILEGES ON \`$__db\`.* TO '$__u'@'$__h';";mysql -u "$__user" -h "$__h" --password="$__pwd" -e "FLUSH PRIVILEGES;";echo -e $__p &> $HUB_HOME/iast.passwd;};
