cluster.name: elastic

node.name: master
node.master: true
node.data: true
network.host: 127.0.0.1
http.port: 9200
transport.tcp.port: 9300

http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: Authorization

indices.fielddata.cache.size:  40%
indices.breaker.fielddata.limit: 60%
indices.breaker.request.limit: 40%
indices.breaker.total.limit: 70%

# bootstrap.memory_lock: true
# cluster.initial_master_nodes:
#     - master

xpack.ml.enabled: false
xpack.security.enabled: true
xpack.license.self_generated.type: basic
xpack.security.transport.ssl.enabled: true

path.data: /humsys/hub.d/elasticsearch
path.logs: /humlog/elasticsearch